runtime settings/filetypes/cpp.vim
runtime settings/filetypes/csharp.vim
runtime settings/filetypes/html.vim
runtime settings/filetypes/makefile.vim
runtime settings/filetypes/markdown.vim
runtime settings/filetypes/python.vim
runtime settings/filetypes/shell.vim
runtime settings/filetypes/vimfile.vim
runtime settings/filetypes/vue.vim
runtime settings/filetypes/yaml.vim
